filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.jsonl
    json.keys_under_root: true
    json.add_error_key: true

processors:
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "aggregate-logs-%{+yyyy.MM.dd}"

setup.template.enabled: false
setup.ilm.enabled: false
